apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: zdeno
spec:
  rules:
  - host: ngtesticek.wuestenrot.sk
    http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: nginx
          port:
           number: 80